}

// Initial Voice Models (LIVING US Presidents & Living Celebrities ONLY)
let voiceModels: DBVoiceModel[] = [
  // --- LIVING US PRESIDENTS ---
  {
    id: 'pres-barack-obama',
    name: 'Barack Obama — Audacity & Cadence',
    description: 'Signature cadenced baritone with measured dramatic pauses, vocal resonance, and rhythmic rhetoric.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'adult',
    accent: 'Chicago / General American',
    baseVoiceName: 'Zephyr',
    sampleAudioUrl: 'https://drive.google.com/drive/folders/1ymyE2f2Y7gNf7PIzYe_UHp7JpcmeuHif?usp=sharing',
    transcriptSample: 'As a prominent figure of the free world, I believe we are responsible for being philanthropists.',
    tags: ['President', 'Obama', 'Living', 'Baritone', 'Orator'],
    isCloned: false,
    vocalProfile: {
      fundamentalPitchHz: 102,
      pitchRangeHz: [78, 160],
      speechCadenceWpm: 130,
      warmthScore: 96,
      clarityScore: 98,
      resonantFormants: [470, 1490, 2460, 3480],
      embeddingVectorPreview: [0.29, -0.51, 0.84, 0.17, -0.33, 0.72, 0.14, -0.18],
      noiseFloorDb: -67,
      recommendedSpeed: 0.95,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pres-donald-trump',
    name: 'Donald Trump — Mar-a-Lago Executive',
    description: 'Expressive, highly emphatic delivery with signature Queens New York cadence and bold executive presence.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Queens New York Executive',
    baseVoiceName: 'Puck',
    sampleAudioUrl: 'https://drive.google.com/drive/folders/1ymyE2f2Y7gNf7PIzYe_UHp7JpcmeuHif?usp=sharing',
    transcriptSample: 'We are going to make big, unbelievable progress, folks. Nobody does it better than us.',
    tags: ['President', 'Trump', 'Living', 'Executive', 'New York'],
    isCloned: false,
    vocalProfile: {
      fundamentalPitchHz: 115,
      pitchRangeHz: [88, 195],
      speechCadenceWpm: 148,
      warmthScore: 88,
      clarityScore: 95,
      resonantFormants: [525, 1610, 2640, 3710],
      embeddingVectorPreview: [-0.38, 0.81, -0.19, 0.47, -0.62, 0.35, 0.89, -0.04],
      noiseFloorDb: -59,
      recommendedSpeed: 1.02,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pres-joe-biden',
    name: 'Joe Biden — Scranton Oval Address',
    description: 'Gravely, candid, conversational Scranton tone with authentic mid-Atlantic cadence and empathetic inflection.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Scranton / Mid-Atlantic Baritone',
    baseVoiceName: 'Charon',
    sampleAudioUrl: 'https://drive.google.com/drive/folders/1ymyE2f2Y7gNf7PIzYe_UHp7JpcmeuHif?usp=sharing',
    transcriptSample: 'Here is the deal, folks. We must stand united and build a brighter future for everyone.',
    tags: ['President', 'Biden', 'Living', 'Conversational', 'Scranton'],
    isCloned: false,
    vocalProfile: {
      fundamentalPitchHz: 112,
      pitchRangeHz: [85, 170],
      speechCadenceWpm: 125,
      warmthScore: 93,
      clarityScore: 91,
      resonantFormants: [500, 1540, 2520, 3550],
      embeddingVectorPreview: [0.11, 0.39, -0.52, 0.67, -0.28, 0.44, 0.61, -0.12],
      noiseFloorDb: -62,
      recommendedSpeed: 0.92,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pres-george-w-bush',
    name: 'George W. Bush — Texas Oval Address',
    description: 'Direct, earnest Texas drawl cadence tuned for concise policy briefings and clear leadership.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Texas / Southern Baritone',
    baseVoiceName: 'Puck',
    sampleAudioUrl: 'https://drive.google.com/drive/folders/1ymyE2f2Y7gNf7PIzYe_UHp7JpcmeuHif?usp=sharing',
    transcriptSample: 'We will not tire, we will not falter, and we will not fail.',
    tags: ['President', 'Bush', 'Living', 'Texas', 'Oval Address'],
    isCloned: false,
    vocalProfile: {
      fundamentalPitchHz: 118,
      pitchRangeHz: [90, 185],
      speechCadenceWpm: 142,
      warmthScore: 91,
      clarityScore: 93,
      resonantFormants: [510, 1580, 2600, 3650],
      embeddingVectorPreview: [-0.15, 0.48, 0.62, -0.25, 0.53, -0.18, 0.79, 0.26],
      noiseFloorDb: -61,
      recommendedSpeed: 1.0,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pres-bill-clinton',
    name: 'Bill Clinton — Hope Arkansas Baritone',
    description: 'Smooth, charismatic Arkansas baritone with warm conversational drawl, persuasive cadence, and storytelling style.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Hope Arkansas / Southern Baritone',
    baseVoiceName: 'Fenrir',
    sampleAudioUrl: 'https://drive.google.com/drive/folders/1ymyE2f2Y7gNf7PIzYe_UHp7JpcmeuHif?usp=sharing',
    transcriptSample: 'There is nothing wrong with America that cannot be cured by what is right with America.',
    tags: ['President', 'Clinton', 'Living', 'Arkansas', 'Charismatic'],
    isCloned: false,
    vocalProfile: {
      fundamentalPitchHz: 104,
      pitchRangeHz: [80, 160],
      speechCadenceWpm: 135,
      warmthScore: 97,
      clarityScore: 95,
      resonantFormants: [480, 1500, 2480, 3490],
      embeddingVectorPreview: [0.18, 0.42, 0.79, -0.21, 0.62, -0.14, 0.85, 0.22],
      noiseFloorDb: -65,
      recommendedSpeed: 0.96,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- LIVING CELEBRITIES ---
  {
    id: 'celeb-morgan-freeman',
    name: 'Morgan Freeman — Deep Resonant Narrator',
    description: 'Unmistakable deep, warm, authoritative baritone with legendary cinematic narration warmth and gravitas.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Memphis / Cinematic Deep Baritone',
    baseVoiceName: 'Fenrir',
    tags: ['Celebrity', 'Freeman', 'Living', 'Narrator', 'Deep'],
    isCloned: false,
    vocalProfile: {
      fundamentalPitchHz: 82,
      pitchRangeHz: [58, 125],
      speechCadenceWpm: 118,
      warmthScore: 99,
      clarityScore: 97,
      resonantFormants: [400, 1320, 2250, 3100],
      embeddingVectorPreview: [0.88, -0.72, 0.95, 0.12, -0.45, 0.82, 0.09, -0.31],
      noiseFloorDb: -68,
      recommendedSpeed: 0.88,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'celeb-arnold-schwarzenegger',
    name: 'Arnold Schwarzenegger — Action Icon Baritone',
    description: 'Bold, rhythmic action hero voice with iconic Austrian accent, commanding volume, and legendary movie delivery.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Austrian / Action Hero Baritone',
    baseVoiceName: 'Puck',
    tags: ['Celebrity', 'Arnold', 'Living', 'Action Hero', 'Austrian'],
    isCloned: false,
    vocalProfile: {
      fundamentalPitchHz: 125,
      pitchRangeHz: [95, 200],
      speechCadenceWpm: 145,
      warmthScore: 89,
      clarityScore: 94,
      resonantFormants: [540, 1650, 2700, 3800],
      embeddingVectorPreview: [-0.45, 0.78, -0.22, 0.55, -0.68, 0.38, 0.82, -0.11],
      noiseFloorDb: -58,
      recommendedSpeed: 1.0,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'celeb-david-attenborough',
    name: 'David Attenborough — Natural History Narrator',
    description: 'Revered British natural history narrator with gentle, wonder-filled, whispery cadence and crystal-clear articulation.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'RP British Broadcasting',
    baseVoiceName: 'Zephyr',
    tags: ['Celebrity', 'Attenborough', 'Living', 'British', 'Nature'],
    isCloned: false,
    vocalProfile: {
      fundamentalPitchHz: 110,
      pitchRangeHz: [85, 165],
      speechCadenceWpm: 122,
      warmthScore: 98,
      clarityScore: 99,
      resonantFormants: [490, 1520, 2500, 3520],
      embeddingVectorPreview: [0.15, 0.32, -0.48, 0.72, 0.22, -0.75, 0.48, 0.31],
      noiseFloorDb: -66,
      recommendedSpeed: 0.9,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'celeb-christopher-walken',
    name: 'Christopher Walken — Rhythmic Cadence Legend',
    description: 'Iconic Queens staccato delivery with unpredictable speech rhythms, dramatic pauses, and eccentric cadence.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Queens NY Staccato',
    baseVoiceName: 'Charon',
    tags: ['Celebrity', 'Walken', 'Living', 'Staccato', 'Iconic'],
    isCloned: false,
    vocalProfile: {
      fundamentalPitchHz: 116,
      pitchRangeHz: [80, 190],
      speechCadenceWpm: 128,
      warmthScore: 91,
      clarityScore: 92,
      resonantFormants: [515, 1590, 2610, 3680],
      embeddingVectorPreview: [-0.28, 0.65, 0.34, -0.58, 0.41, 0.79, -0.22, 0.48],
      noiseFloorDb: -60,
      recommendedSpeed: 0.92,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'celeb-samuel-l-jackson',
    name: 'Samuel L. Jackson — Bold Expressive Voice',
    description: 'Powerful, intense, highly expressive voice with sharp emphasis, commanding volume, and legendary punch.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Chattanooga / Bold American',
    baseVoiceName: 'Puck',
    tags: ['Celebrity', 'Jackson', 'Living', 'Bold', 'Dramatic'],
    isCloned: false,
    vocalProfile: {
      fundamentalPitchHz: 120,
      pitchRangeHz: [92, 210],
      speechCadenceWpm: 155,
      warmthScore: 88,
      clarityScore: 96,
      resonantFormants: [530, 1630, 2680, 3750],
      embeddingVectorPreview: [-0.42, 0.84, -0.15, 0.51, -0.61, 0.42, 0.88, -0.08],
      noiseFloorDb: -57,
      recommendedSpeed: 1.05,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'celeb-keanu-reeves',
    name: 'Keanu Reeves — Chill Action Tone',
    description: 'Cool, relaxed, grounded baritone with serene conversational tone and thoughtful delivery.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'adult',
    accent: 'West Coast / Canadian Cool',
    baseVoiceName: 'Zephyr',
    tags: ['Celebrity', 'Keanu', 'Living', 'Cool', 'Grounded'],
    isCloned: false,
    vocalProfile: {
      fundamentalPitchHz: 108,
      pitchRangeHz: [82, 155],
      speechCadenceWpm: 125,
      warmthScore: 94,
      clarityScore: 93,
      resonantFormants: [485, 1495, 2470, 3490],
      embeddingVectorPreview: [0.12, -0.38, 0.72, 0.31, -0.15, 0.68, 0.25, -0.12],
      noiseFloorDb: -63,
      recommendedSpeed: 0.94,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'celeb-oprah-winfrey',
    name: 'Oprah Winfrey — Inspiring Warm Broadcaster',
    description: 'Resonant, highly inspiring broadcast voice with warm empathetic inflection and powerful public speaking resonance.',
    category: 'preselected',
    gender: 'female',
    ageGroup: 'mature',
    accent: 'General American Broadcast',
    baseVoiceName: 'Kore',
    tags: ['Celebrity', 'Oprah', 'Living', 'Inspiring', 'Broadcast'],
    isCloned: false,
    vocalProfile: {
      fundamentalPitchHz: 195,
      pitchRangeHz: [155, 260],
      speechCadenceWpm: 145,
      warmthScore: 98,
      clarityScore: 97,
      resonantFormants: [560, 1680, 2750, 3850],
      embeddingVectorPreview: [-0.22, 0.58, 0.28, -0.72, 0.49, -0.12, 0.88, 0.24],
      noiseFloorDb: -65,
      recommendedSpeed: 0.98,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

let generatedClips: DBClip[] = [];

// Auto-delete custom voice models and generated audio clips created more than 5 minutes ago (300,000 ms)
function autoPruneExpiredItems() {
  const now = Date.now();
  const FIVE_MINUTES_MS = 5 * 60 * 1000;

  // Prune custom/cloned voice models older than 5 minutes
  voiceModels = voiceModels.filter((model) => {
    if (!model.isCloned && model.category !== 'custom') return true; // Keep default pre-seeded library
    if (!model.createdAt) return true;
    const age = now - new Date(model.createdAt).getTime();
    return age <= FIVE_MINUTES_MS;
  });

  // Prune generated audio clips older than 5 minutes
  generatedClips = generatedClips.filter((clip) => {
    if (!clip.createdAt) return true;
    const age = now - new Date(clip.createdAt).getTime();
    return age <= FIVE_MINUTES_MS;
  });
}

// Periodically prune expired items every 10 seconds
setInterval(autoPruneExpiredItems, 10000);

// ================= API ENDPOINTS =================
