const fs = require('fs');
let code = fs.readFileSync('src/services/api.ts', 'utf8');

const replacement = `const PRESELECTED_LIBRARY: VoiceModel[] = [
  {
    id: 'pres-barack-obama',
    name: 'Barack Obama — Audacity & Cadence',
    description: 'Signature cadenced baritone with measured dramatic pauses, vocal resonance, and rhythmic rhetoric.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'adult',
    accent: 'Chicago / General American',
    baseVoiceName: 'Zephyr',
    sampleAudioUrl: 'https://drive.google.com/drive/folders/1ymyE2f2Y7gNf7PIzYe_UHp7JpcmeuHif?usp=sharing',
    tags: ['President', 'Obama', 'Living', 'Baritone', 'Orator'],
    isCloned: false,
    vocalflowProfile: {
      fundamentalPitchHz: 110,
      pitchRangeHz: [85, 175],
      speechCadenceWpm: 135,
      warmthScore: 98,
      clarityScore: 95,
      resonantFormants: [450, 1450, 2400, 3400],
      embeddingVectorPreview: [0.29, -0.51, 0.84, 0.17, -0.33, 0.72, 0.14, -0.18],
      noiseFloorDb: -64,
      recommendedSpeed: 0.92,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pres-donald-trump',
    name: 'Donald Trump — Executive Address',
    description: 'Distinctive Queens accent with assertive volume, declarative rhythmic delivery, and signature emphasis.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Queens NY / Executive',
    baseVoiceName: 'Puck',
    sampleAudioUrl: 'https://drive.google.com/drive/folders/1ymyE2f2Y7gNf7PIzYe_UHp7JpcmeuHif?usp=sharing',
    tags: ['President', 'Trump', 'Living', 'Executive', 'Loud'],
    isCloned: false,
    vocalflowProfile: {
      fundamentalPitchHz: 132,
      pitchRangeHz: [100, 190],
      speechCadenceWpm: 142,
      warmthScore: 55,
      clarityScore: 85,
      resonantFormants: [500, 1600, 2600, 3600],
      embeddingVectorPreview: [-0.62, 0.71, -0.15, 0.44, -0.88, 0.22, 0.91, -0.34],
      noiseFloorDb: -58,
      recommendedSpeed: 1.0,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pres-joe-biden',
    name: 'Joe Biden — Scranton Empathy',
    description: 'Measured, folksy older statesman delivery with empathetic warmth, gentle rasp, and breathy cadence.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Scranton PA / General American',
    baseVoiceName: 'Fenrir',
    sampleAudioUrl: 'https://drive.google.com/drive/folders/1ymyE2f2Y7gNf7PIzYe_UHp7JpcmeuHif?usp=sharing',
    tags: ['President', 'Biden', 'Living', 'Folksy', 'Warm'],
    isCloned: false,
    vocalflowProfile: {
      fundamentalPitchHz: 108,
      pitchRangeHz: [80, 160],
      speechCadenceWpm: 130,
      warmthScore: 85,
      clarityScore: 75,
      resonantFormants: [480, 1500, 2500, 3500],
      embeddingVectorPreview: [0.15, -0.22, 0.68, 0.45, 0.12, -0.55, 0.38, 0.61],
      noiseFloorDb: -62,
      recommendedSpeed: 0.95,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pres-george-w-bush',
    name: 'George W. Bush — Texas Baritone',
    description: 'Warm Texas drawl with conversational tone, slightly rhythmic cadence, and friendly mid-range projection.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Texas / Midland American',
    baseVoiceName: 'Charon',
    sampleAudioUrl: 'https://drive.google.com/drive/folders/1ymyE2f2Y7gNf7PIzYe_UHp7JpcmeuHif?usp=sharing',
    tags: ['President', 'Bush', 'Living', 'Texas', 'Drawl'],
    isCloned: false,
    vocalflowProfile: {
      fundamentalPitchHz: 130,
      pitchRangeHz: [95, 185],
      speechCadenceWpm: 155,
      warmthScore: 82,
      clarityScore: 88,
      resonantFormants: [510, 1550, 2550, 3550],
      embeddingVectorPreview: [0.42, 0.15, -0.31, -0.66, 0.55, -0.19, 0.72, 0.11],
      noiseFloorDb: -65,
      recommendedSpeed: 1.0,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pres-bill-clinton',
    name: 'Bill Clinton — Hope Arkansas Baritone',
    description: 'Smooth, charismatic Arkansas baritone with warm conversational drawl, persuasive cadence, and storytelling style.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Hope Arkansas / Southern Baritone',
    baseVoiceName: 'Fenrir',
    sampleAudioUrl: 'https://drive.google.com/drive/folders/1ymyE2f2Y7gNf7PIzYe_UHp7JpcmeuHif?usp=sharing',
    tags: ['President', 'Clinton', 'Living', 'Arkansas', 'Charismatic'],
    isCloned: false,
    vocalflowProfile: {
      fundamentalPitchHz: 102,
      pitchRangeHz: [75, 160],
      speechCadenceWpm: 140,
      warmthScore: 96,
      clarityScore: 90,
      resonantFormants: [460, 1420, 2420, 3450],
      embeddingVectorPreview: [0.18, 0.42, 0.79, -0.21, 0.62, -0.14, 0.85, 0.22],
      noiseFloorDb: -65,
      recommendedSpeed: 0.96,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'celeb-morgan-freeman',
    name: 'Morgan Freeman — Deep Resonant Narrator',
    description: 'Unmistakable deep, warm, authoritative baritone with legendary cinematic narration warmth and gravitas.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Memphis / Cinematic Deep Baritone',
    baseVoiceName: 'Fenrir',
    tags: ['Celebrity', 'Freeman', 'Living', 'Narrator', 'Deep'],
    isCloned: false,
    vocalflowProfile: {
      fundamentalPitchHz: 85,
      pitchRangeHz: [60, 120],
      speechCadenceWpm: 110,
      warmthScore: 99,
      clarityScore: 98,
      resonantFormants: [380, 1250, 2150, 3050],
      embeddingVectorPreview: [0.88, -0.72, 0.95, 0.12, -0.45, 0.82, 0.09, -0.31],
      noiseFloorDb: -68,
      recommendedSpeed: 0.88,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'celeb-arnold-schwarzenegger',
    name: 'Arnold Schwarzenegger — Action Icon Baritone',
    description: 'Bold, rhythmic action hero voice with iconic Austrian accent, commanding volume, and legendary movie delivery.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Austrian / Action Hero Baritone',
    baseVoiceName: 'Puck',
    tags: ['Celebrity', 'Arnold', 'Living', 'Action Hero', 'Austrian'],
    isCloned: false,
    vocalflowProfile: {
      fundamentalPitchHz: 105,
      pitchRangeHz: [75, 165],
      speechCadenceWpm: 118,
      warmthScore: 65,
      clarityScore: 82,
      resonantFormants: [520, 1520, 2520, 3520],
      embeddingVectorPreview: [-0.45, 0.78, -0.22, 0.55, -0.68, 0.38, 0.82, -0.11],
      noiseFloorDb: -58,
      recommendedSpeed: 1.0,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'celeb-david-attenborough',
    name: 'David Attenborough — Natural History Narrator',
    description: 'Revered British natural history narrator with gentle, wonder-filled, whispery cadence and crystal-clear articulation.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'RP British Broadcasting',
    baseVoiceName: 'Zephyr',
    tags: ['Celebrity', 'Attenborough', 'Living', 'British', 'Nature'],
    isCloned: false,
    vocalflowProfile: {
      fundamentalPitchHz: 115,
      pitchRangeHz: [85, 180],
      speechCadenceWpm: 125,
      warmthScore: 96,
      clarityScore: 98,
      resonantFormants: [490, 1490, 2490, 3490],
      embeddingVectorPreview: [0.15, 0.32, -0.48, 0.72, 0.22, -0.75, 0.48, 0.31],
      noiseFloorDb: -66,
      recommendedSpeed: 0.9,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'celeb-christopher-walken',
    name: 'Christopher Walken — Rhythmic Cadence Legend',
    description: 'Iconic Queens staccato delivery with unpredictable speech rhythms, dramatic pauses, and eccentric cadence.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Queens NY Staccato',
    baseVoiceName: 'Charon',
    tags: ['Celebrity', 'Walken', 'Living', 'Staccato', 'Iconic'],
    isCloned: false,
    vocalflowProfile: {
      fundamentalPitchHz: 112,
      pitchRangeHz: [80, 180],
      speechCadenceWpm: 105,
      warmthScore: 75,
      clarityScore: 88,
      resonantFormants: [505, 1505, 2505, 3505],
      embeddingVectorPreview: [-0.28, 0.65, 0.34, -0.58, 0.41, 0.79, -0.22, 0.48],
      noiseFloorDb: -60,
      recommendedSpeed: 0.92,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'celeb-samuel-l-jackson',
    name: 'Samuel L. Jackson — Bold Expressive Voice',
    description: 'Powerful, intense, highly expressive voice with sharp emphasis, commanding volume, and legendary punch.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'mature',
    accent: 'Chattanooga / Bold American',
    baseVoiceName: 'Puck',
    tags: ['Celebrity', 'Jackson', 'Living', 'Bold', 'Dramatic'],
    isCloned: false,
    vocalflowProfile: {
      fundamentalPitchHz: 118,
      pitchRangeHz: [85, 195],
      speechCadenceWpm: 165,
      warmthScore: 70,
      clarityScore: 95,
      resonantFormants: [515, 1515, 2515, 3515],
      embeddingVectorPreview: [-0.42, 0.84, -0.15, 0.51, -0.61, 0.42, 0.88, -0.08],
      noiseFloorDb: -57,
      recommendedSpeed: 1.05,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'celeb-keanu-reeves',
    name: 'Keanu Reeves — Chill Action Tone',
    description: 'Cool, relaxed, grounded baritone with serene conversational tone and thoughtful delivery.',
    category: 'preselected',
    gender: 'male',
    ageGroup: 'adult',
    accent: 'West Coast / Canadian Cool',
    baseVoiceName: 'Zephyr',
    tags: ['Celebrity', 'Keanu', 'Living', 'Cool', 'Grounded'],
    isCloned: false,
    vocalflowProfile: {
      fundamentalPitchHz: 100,
      pitchRangeHz: [75, 145],
      speechCadenceWpm: 115,
      warmthScore: 85,
      clarityScore: 85,
      resonantFormants: [475, 1475, 2475, 3475],
      embeddingVectorPreview: [0.12, -0.38, 0.72, 0.31, -0.15, 0.68, 0.25, -0.12],
      noiseFloorDb: -63,
      recommendedSpeed: 0.94,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'celeb-oprah-winfrey',
    name: 'Oprah Winfrey — Inspiring Warm Broadcaster',
    description: 'Resonant, highly inspiring broadcast voice with warm empathetic inflection and powerful public speaking resonance.',
    category: 'preselected',
    gender: 'female',
    ageGroup: 'mature',
    accent: 'General American Broadcast',
    baseVoiceName: 'Kore',
    tags: ['Celebrity', 'Oprah', 'Living', 'Inspiring', 'Broadcast'],
    isCloned: false,
    vocalflowProfile: {
      fundamentalPitchHz: 195,
      pitchRangeHz: [140, 280],
      speechCadenceWpm: 150,
      warmthScore: 97,
      clarityScore: 97,
      resonantFormants: [600, 1600, 2600, 3600],
      embeddingVectorPreview: [-0.22, 0.58, 0.28, -0.72, 0.49, -0.12, 0.88, 0.24],
      noiseFloorDb: -65,
      recommendedSpeed: 0.98,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];`;

const startIdx = code.indexOf('const PRESELECTED_LIBRARY: VoiceModel[] = [');
const endIdx = code.indexOf('];\n', startIdx) + 3;

if (startIdx !== -1 && endIdx !== -1) {
  code = code.substring(0, startIdx) + replacement + code.substring(endIdx);
  fs.writeFileSync('src/services/api.ts', code);
}
